apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-gateway-grpc-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.3"
  POD_NAME: "go-gateway-grpc.eks-arch-01-02"
  PORT: "6000"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  DB_MAX_CONNECTION: "8"
  CTX_TIMEOUT: "5"
  SETPOD_AZ: "false"
  ENV: "dev"

  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-02-otel-collector-collector.default.svc.cluster.local:4317"
  USE_STDOUT_TRACER_EXPORTER: "false"
  USE_OTLP_COLLECTOR: "true" 
  AWS_CLOUDWATCH_LOG_GROUP_NAMES: "/dock/eks/eks-arch-01-02"

  NAME_SERVICE_00: "go-payment-authorizer"
  URL_SERVICE_00: "dns:///svc-go-payment-authorizer.test-a.svc.cluster.local:65000" #"dns:///127.0.0.1:65000"

  NAME_SERVICE_01: "go-payment-gateway"
  URL_SERVICE_01: "https://nlb-eks-arch-01-02.architecture.caradhras.io"
  METHOD_SERVICE_01: "POST"
  HOST_SERVICE_01: "go-payment-gateway.architecture.caradhras.io"
  CLIENT_HTTP_TIMEOUT_01: "5"